// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apbd_cw7_EntityFramework.DAL;

#nullable disable

namespace apbd_cw7_EntityFramework.Migrations
{
    [DbContext(typeof(PcsDbContext))]
    [Migration("20260516162815_AddRemainingTables")]
    partial class AddRemainingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("s33985")
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components", "s33985");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers", "s33985");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes", "s33985");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs", "s33985");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.PcComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents", "s33985");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.Component", b =>
                {
                    b.HasOne("apbd_cw7_EntityFramework.Entities.ComponentManufacturer", "Manufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_cw7_EntityFramework.Entities.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.PcComponent", b =>
                {
                    b.HasOne("apbd_cw7_EntityFramework.Entities.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_cw7_EntityFramework.Entities.Pc", "Pc")
                        .WithMany("PcComponents")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.Pc", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
