// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apbd_cw7_EntityFramework.DAL;

#nullable disable

namespace apbd_cw7_EntityFramework.Migrations
{
    [DbContext(typeof(PcsDbContext))]
    partial class PcsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("s33985")
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components", "s33985");

                    b.HasData(
                        new
                        {
                            Code = "I9-14900K",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 1,
                            Description = "High-end desktop processor",
                            Name = "Intel Core i9-14900K"
                        },
                        new
                        {
                            Code = "RX7900XTX",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 2,
                            Description = "Flagship AMD graphics card",
                            Name = "AMD Radeon RX 7900 XTX"
                        },
                        new
                        {
                            Code = "RTX4090",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 2,
                            Description = "Top-tier Nvidia GPU",
                            Name = "Nvidia GeForce RTX 4090"
                        },
                        new
                        {
                            Code = "R9-7950X",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 1,
                            Description = "16-core workstation CPU",
                            Name = "AMD Ryzen 9 7950X"
                        });
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers", "s33985");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INTEL",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1969, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nvidia Corporation"
                        });
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes", "s33985");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SSD",
                            Name = "Solid State Drive"
                        });
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs", "s33985");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workstation Ultra",
                            Stock = 3,
                            Warranty = 48,
                            Weight = 18f
                        });
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.PcComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents", "s33985");

                    b.HasData(
                        new
                        {
                            PcId = 1,
                            ComponentCode = "I9-14900K",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "RTX4090",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "R9-7950X",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "I9-14900K",
                            Amount = 2
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "RX7900XTX",
                            Amount = 2
                        });
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.Component", b =>
                {
                    b.HasOne("apbd_cw7_EntityFramework.Entities.ComponentManufacturer", "Manufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_cw7_EntityFramework.Entities.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.PcComponent", b =>
                {
                    b.HasOne("apbd_cw7_EntityFramework.Entities.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_cw7_EntityFramework.Entities.Pc", "Pc")
                        .WithMany("PcComponents")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("apbd_cw7_EntityFramework.Entities.Pc", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
